image:
  repository: ghcr.io/tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.14.5@sha256:7030166d0b05429ffd9da026936ba2d0a6898831fdad153988d7825c4c827f8e
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
